export default [
    {
    "name": "abacus",
    "description": "Hack-a-Week 17: An abacus desktop app using electron. ",
    "created_at": "2017-03-19T13:29:14Z",
    "language": "JavaScript",
    "fork": false,
  },
  {
    "name": "absolutely_nothing",
    "description": "The only code that never breaks. Ever. http://ztaira14.github.io/absolutely_nothing",
    "created_at": "2016-04-10T04:20:26Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "aes_python",
    "description": "Hack-A-Week 1: An attempt at implementing the AES in python, for funsies.",
    "created_at": "2016-07-03T14:47:04Z",
    "language": "HTML",
    "fork": false,
  },
  {
    "name": "bsmsViz",
    "description": "Hack-A-Week 16: Visualizing the BS/MS program's depth courses in Northeastern's ECE Department",
    "created_at": "2017-02-03T19:03:29Z",
    "language": "JavaScript",
    "fork": false,
  },
  {
    "name": "donkey.zach",
    "description": "Hack-A-Week 3: ASCII racing game inspired by the legendary DONKEY.BAS.",
    "created_at": "2016-07-19T20:56:52Z",
    "language": "C++",
    "fork": false,
  },
  {
    "name": "dotfiles",
    "description": "Everything I need to to set up my personal coding environment. ",
    "created_at": "2016-03-29T15:18:55Z",
    "language": "Vim script",
    "fork": false,
  },
  {
    "name": "Email_Sender",
    "description": "Small email sender in Tkinter. Reads default email from a text file. Uses gmail. ",
    "created_at": "2016-03-05T00:17:59Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "evil_maid_suite",
    "description": "Hack-A-Week 10: Data visualization on the time I keylogged myself",
    "created_at": "2016-09-24T02:34:38Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "fb_creeper",
    "description": "Hack-A-Week 13: Python script to programmatically watch fb chat for you",
    "created_at": "2016-11-27T02:57:35Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "flappy_term",
    "description": "Hack-A-Week 4: ASCII Flappy Bird clone using ncurses. ",
    "created_at": "2016-07-30T05:19:14Z",
    "language": "C++",
    "fork": false,
  },
  {
    "name": "gitbub",
    "description": "Hack-A-Week 15: Fun Github visualization using d3",
    "created_at": "2017-01-25T16:54:22Z",
    "language": "JavaScript",
    "fork": false,
  },
  {
    "name": "hackaweek",
    "description": "Hack-A-Week 8.5: An example skeleton for all my hack-a-weeks. ",
    "created_at": "2016-09-06T20:38:16Z",
    "language": null,
    "fork": false,
  },
  {
    "name": "HighChartsTest",
    "description": "A graph using highcharts",
    "created_at": "2016-02-26T17:27:30Z",
    "language": "HTML",
    "fork": false,
  },
  {
    "name": "httplescripts",
    "description": "Hack-A-Week 14 w/ shoarora: Run applescripts remotely via HTTP requests",
    "created_at": "2016-12-29T00:29:09Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "hub_where",
    "description": "Hack-A-Week 11 and 12: Python scripts to gather and visualize data from Hubway's bike-sharing stations. ",
    "created_at": "2016-10-02T06:12:26Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "journal",
    "description": "A public journal",
    "created_at": "2017-05-29T14:55:15Z",
    "language": null,
    "fork": false,
  },
  {
    "name": "JSTest",
    "description": "This test bounces a ball.",
    "created_at": "2016-02-26T17:24:41Z",
    "language": "JavaScript",
    "fork": false,
  },
  {
    "name": "keylogger",
    "description": "A no-frills keylogger for Mac OS X.",
    "created_at": "2016-09-24T02:27:38Z",
    "language": "C",
  },
  {
    "name": "myhistory",
    "description": "Small wrapper to make using IDLE better. ",
    "created_at": "2016-02-17T17:15:04Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "pretty-reqs",
    "description": "Hack-a-Week 18: A plain text graph editor, written with react. ",
    "created_at": "2017-04-05T15:54:46Z",
    "language": "JavaScript",
    "fork": false,
  },
  {
    "name": "PythonGame",
    "description": "It's a bullet hell game in Python. It's pretty slow when too many objects are on the screen. Uses tkinter.",
    "created_at": "2016-03-05T00:21:00Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "python_flow",
    "description": "Hack-A-Week 2: A python flow visualizer in c++. Inspired by git log --graph.",
    "created_at": "2016-07-15T19:16:05Z",
    "language": "C++",
    "fork": false,
  },
  {
    "name": "RubiksGUI",
    "description": "A rubiks cube, implemented in tkinter. Operational via button input or key press. ",
    "created_at": "2016-03-05T00:27:07Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "souper_trawler",
    "description": "Hack-A-Week 9: A python script to scan a webpage and pull down relevant files.",
    "created_at": "2016-09-10T18:10:05Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "TSA-Travel-Sentry-master-keys",
    "description": "3D reproduction of TSA Master keys",
    "created_at": "2016-07-28T14:55:38Z",
    "language": null,
  },
  {
    "name": "TwitterBot",
    "description": "My first TwitterBot! :D",
    "created_at": "2016-02-29T05:21:51Z",
    "language": "Python",
    "fork": false,
  },
  {
    "name": "uku_tabs",
    "description": "Hack-A-Week 6 and 7: A terminal-based guitar/ukulele tab management tool. ",
    "created_at": "2016-08-15T20:12:50Z",
    "language": "C++",
    "fork": false,
  },
  {
    "name": "vim_notes",
    "description": "Hack-A-Week 5: A vim folding file for my notes. ",
    "created_at": "2016-08-02T03:53:37Z",
    "language": "VimL",
    "fork": false,
  },
  {
    "name": "whiz",
    "description": "A bookmark function for the terminal, because 'cd' is too slow. ",
    "created_at": "2016-08-30T17:03:01Z",
    "language": "Shell",
    "fork": false,
  },
  {
    "name": "zachs_resume",
    "description": "Hack-a-Week 8: My resume in LaTeX",
    "created_at": "2016-09-06T20:34:28Z",
    "language": "TeX",
    "fork": false,
   }
  ];
